export enum CampaignType {
  PRODUCT_LAUNCH = 'Product Launch',
  FLASH_SALE = 'Flash Sale / Limited Time',
  ABANDONED_CART = 'Abandoned Cart Recovery',
  UPSELL_CROSS_SELL = 'Upsell / Cross-sell',
  SEASONAL = 'Seasonal Campaigns',
  FREE_SHIPPING = 'Free Shipping Promo',
  CUSTOMER_REACTIVATION = 'Customer Reactivation',
  BESTSELLER_BOOST = 'Bestseller Boost',
  HIGH_ROAS_BOOSTER = 'High ROAS Booster',
  SLOW_MOVER_PUSH = 'Slow-Mover Inventory Push',
}

export enum CampaignStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  READY_TO_LAUNCH = 'READY_TO_LAUNCH',
  PROCESSED = 'PROCESSED',
  LIVE = 'LIVE',
  FAILED_TO_LAUNCH = 'FAILED_TO_LAUNCH',
}

export enum CampaignPlatform {
  FACEBOOK = 'FACEBOOK',
  INSTAGRAM = 'INSTAGRAM',
  GOOGLE = 'GOOGLE',
}

export enum GoogleAdsProcessingStatus {
  PENDING = 'PENDING',
  INITIALIZING = 'INITIALIZING',
  INITIALIZED = 'INITIALIZED',
  CREATING_CUSTOMER = 'CREATING_CUSTOMER',
  CUSTOMER_CREATED = 'CUSTOMER_CREATED',
  CREATING_BUDGET = 'CREATING_BUDGET',
  CREATING_BIDDING_STRATEGY = 'CREATING_BIDDING_STRATEGY',
  CREATING_CAMPAIGN = 'CREATING_CAMPAIGN',
  CREATING_AD_GROUPS = 'CREATING_AD_GROUPS',
  AD_GROUPS_CREATED = 'AD_GROUPS_CREATED',
  CREATING_AD_GROUP_ADS = 'CREATING_AD_GROUPS_ADS',
  AD_GROUP_ADS_CREATED = 'AD_GROUP_ADS_CREATED',
  GENERATING_KEYWORDS = 'GENERATING_KEYWORDS',
  KEYWORDS_ADDED = 'KEYWORDS_ADDED',
  ADDING_GEO_TARGETING = 'GEO_TARGETING_ADDED',
  LAUNCHING = 'LAUNCHING',
  LAUNCHED = 'LAUNCHED',
  ACTIVE = 'ACTIVE',
  FAILED = 'FAILED',
}
