export enum ErrorCode {
  E_USER_ALREADY_EXISTS = 'E_USER_ALREADY_EXISTS',
  E_UNVERIFIED_EMAIL = 'E_UNVERIFIED_EMAIL',
  E_USER_NOT_FOUND = 'E_USER_NOT_FOUND',
  E_INVALID_OTP = 'E_INVALID_OTP',
  E_EMAIL_ALREADY_VERIFIED = 'E_EMAIL_ALREADY_VERIFIED',
}
